services:
  #######################################
  ### DEALT MODULE INSTALLER ############
  #######################################
  dealtmodule.installer:
    class: DealtModule\Database\DealtInstaller
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
  #######################################
  ### DEALT MISSION REPO ################
  #######################################
  dealtmodule.doctrine.dealt.mission.repository:
    class: DealtModule\Repository\DealtMissionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtMission
  #######################################
  ### DEALT VIRTUAL PRODUCT REPO ########
  #######################################
  dealtmodule.doctrine.dealt.virtual.product.repository:
    class: DealtModule\Repository\DealtVirtualProductRepository
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $dbPrefix: "%database_prefix%"
