services:
  _defaults:
    public: true
  #######################################
  ### DEALT MISSION REPO ################
  #######################################
  dealtmodule.doctrine.dealt.mission.repository:
    class: DealtModule\Repository\DealtMissionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtMission
  #######################################
  ### DEALT MISSION CATEGORY REPO #######
  #######################################
  dealtmodule.doctrine.dealt.mission.category.repository:
    class: DealtModule\Repository\DealtMissionCategoryRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtMissionCategory
  #######################################
  ### DEALT VIRTUAL PRODUCT REPO ########
  #######################################
  dealtmodule.doctrine.dealt.virtual.product.repository:
    class: DealtModule\Repository\DealtVirtualProductRepository
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
      - "@=container.has('prestashop.adapter.product.repository.product_repository') ? service('prestashop.adapter.product.repository.product_repository') : '~'"
  #######################################
  ### DEALT MODULE INSTALLER ############
  #######################################
  dealtmodule.installer:
    class: DealtModule\Database\DealtInstaller
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
      - "@dealtmodule.doctrine.dealt.mission.repository"
