services:
  _defaults:
    public: true
  #######################################
  ### DEALT SDK SERVICE #################
  #######################################
  dealtmodule.dealt.api.service:
    class: DealtModule\Service\DealtAPIService
    arguments:
      - "@=service('prestashop.adapter.legacy.configuration').get('DEALTMODULE_API_KEY')"
      - "@=service('prestashop.adapter.legacy.configuration').get('DEALTMODULE_PROD_ENV')"
  #######################################
  ### DEALT OFFER REPO ##################
  #######################################
  dealtmodule.doctrine.dealt.offer.repository:
    class: DealtModule\Repository\DealtOfferRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtOffer
  #######################################
  ### DEALT OFFER CATEGORY REPO #########
  #######################################
  dealtmodule.doctrine.dealt.offer.category.repository:
    class: DealtModule\Repository\DealtOfferCategoryRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtOfferCategory
  #######################################
  ### DEALT OFFER CATEGORY REPO #########
  #######################################
  dealtmodule.doctrine.dealt.cart.product.offer.repository:
    class: DealtModule\Repository\DealtCartProductOfferRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtCartProductOffer
  #######################################
  ### DEALT MISSION REPO ################
  #######################################
  dealtmodule.doctrine.dealt.mission.repository:
    class: DealtModule\Repository\DealtMissionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtMission
  #######################################
  ### DEALT VIRTUAL PRODUCT REPO ########
  #######################################
  dealtmodule.doctrine.dealt.virtual.product.repository:
    class: DealtModule\Repository\DealtVirtualProductRepository
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
      - "@=container.has('prestashop.adapter.product.repository.product_repository') ? service('prestashop.adapter.product.repository.product_repository') : '~'"
  #######################################
  ### DEALT MODULE INSTALLER ############
  #######################################
  dealtmodule.installer:
    class: DealtModule\Database\DealtInstaller
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
      - "@dealtmodule.doctrine.dealt.offer.repository"
