services:
  _defaults:
    public: true
  #######################################
  ### DEALT SDK SERVICE #################
  #######################################
  dealtmodule.dealt.api.service:
    class: DealtModule\Service\DealtAPIService
    arguments:
      - "@=service('prestashop.adapter.legacy.configuration').get('DEALTMODULE_API_KEY')"
      - "@=service('prestashop.adapter.legacy.configuration').get('DEALTMODULE_PROD_ENV')"
  #######################################
  ### DEALT CART SERVICE ################
  #######################################
  dealtmodule.dealt.cart.service:
    class: DealtModule\Service\DealtCartService
    arguments:
      - "@dealtmodule.doctrine.dealt.offer.repository"
      - "@dealtmodule.doctrine.dealt.cart.product.ref.repository"
      - "@dealtmodule.presenter.dealt.offer"
  #######################################
  ### DEALT PRODUCT SERVICE #############
  #######################################
  dealtmodule.dealt.product.service:
    class: DealtModule\Service\DealtProductService
    arguments:
      - "@dealtmodule.doctrine.dealt.offer.repository"
      - "@dealtmodule.presenter.dealt.offer"
  #######################################
  ### DEALT ORDER SERVICE ###############
  #######################################
  dealtmodule.dealt.order.service:
    class: DealtModule\Service\DealtOrderService
    arguments:
      - "@dealtmodule.dealt.api.service"
      - "@dealtmodule.doctrine.dealt.mission.repository"
      - "@dealtmodule.doctrine.dealt.offer.repository"
      - "@dealtmodule.doctrine.dealt.cart.product.ref.repository"
      - "@dealtmodule.presenter.dealt.offer"
  #######################################
  ### DEALT OFFER PRESENTER #############
  #######################################
  dealtmodule.presenter.dealt.offer:
    class: DealtModule\Presenter\DealtOfferPresenter
    arguments:
      - "@dealtmodule.doctrine.dealt.cart.product.ref.repository"
      - "@dealtmodule.doctrine.dealt.mission.repository"
  #######################################
  ### DEALT OFFER REPO ##################
  #######################################
  dealtmodule.doctrine.dealt.offer.repository:
    class: DealtModule\Repository\DealtOfferRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtOffer
  #######################################
  ### DEALT OFFER CATEGORY REPO #########
  #######################################
  dealtmodule.doctrine.dealt.offer.category.repository:
    class: DealtModule\Repository\DealtOfferCategoryRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtOfferCategory
  #######################################
  ### DEALT OFFER CATEGORY REPO #########
  #######################################
  dealtmodule.doctrine.dealt.cart.product.ref.repository:
    class: DealtModule\Repository\DealtCartProductRefRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtCartProductRef
  #######################################
  ### DEALT MISSION REPO ################
  #######################################
  dealtmodule.doctrine.dealt.mission.repository:
    class: DealtModule\Repository\DealtMissionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - DealtModule\Entity\DealtMission
  #######################################
  ### DEALT PRODUCT REPO ################
  #######################################
  dealtmodule.doctrine.dealt.product.repository:
    class: DealtModule\Repository\DealtProductRepository
    arguments:
      - "@=container.has('prestashop.adapter.product.repository.product_repository') ? service('prestashop.adapter.product.repository.product_repository') : '~'"
  #######################################
  ### DEALT MODULE INSTALLER ############
  #######################################
  dealtmodule.installer:
    class: DealtModule\Database\DealtInstaller
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
      - "@dealtmodule.doctrine.dealt.offer.repository"
