admin_dealt_configure:
  path: /dealt/configure
  methods: [GET, POST]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtConfigurationController::indexAction'
    _legacy_controller: "AdminDealtConfigurationController"
    _legacy_link: "AdminDealtConfigurationController"
