admin_dealt_configure:
  path: /dealt/configure
  methods: [GET]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtConfigureController::indexAction'
    _legacy_controller: "AdminDealtConfigureController"
    _legacy_link: "AdminDealtConfigureController"
