admin_dealt_configure:
  path: /dealt/configure
  methods: [GET, POST]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtConfigurationController::indexAction'
    _legacy_controller: "AdminDealtConfigurationController"
    _legacy_link: "AdminDealtConfigurationController"
admin_dealt_offer_list:
  path: /dealt/offer/list
  methods: [GET]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtOfferController::indexAction'
    _legacy_controller: "AdminDealtOfferController"
    _legacy_link: "AdminDealtOfferController"
admin_dealt_offer_create:
  path: /dealt/offer/create
  methods: [GET, POST]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtOfferController::createAction'
    _legacy_controller: "AdminDealtOfferController"
    _legacy_link: "AdminDealtOfferController"
admin_dealt_offer_edit:
  path: /dealt/offer/edit/{offerId}
  methods: [GET, POST]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtOfferController::editAction'
    _legacy_controller: "AdminDealtOfferController"
    _legacy_link: "AdminDealtOfferController"
  requirements:
    offerId: \d+
admin_dealt_offer_delete:
  path: /dealt/offer/delete/{offerId}
  methods: [POST]
  defaults:
    _controller: 'DealtModule\Controller\Admin\AdminDealtOfferController::deleteAction'
    _legacy_controller: "AdminDealtOfferController"
    _legacy_link: "AdminDealtOfferController"
  requirements:
    offerId: \d+
