services:
  #######################################
  ### DEALT CONFIGURATION FORM ##########
  #######################################
  dealtmodule.admin.form.configuration.provider:
    class: DealtModule\Forms\Admin\DealtConfigurationFormDataProvider
    arguments:
      $configuration: "@prestashop.adapter.legacy.configuration"
  dealtmodule.admin.form.configuration.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $formDataProvider: "@dealtmodule.admin.form.configuration.provider"
      $formTypes:
        configuration: 'DealtModule\Forms\Admin\DealtConfigurationFormType'
      $hookName: "AdminDealtModuleConfiguration"
  #######################################
  ### DEALT OFFER FORM ##################
  #######################################
  dealtmodule.admin.form.offer.data.provider:
    class: DealtModule\Forms\Admin\DealtOfferFormDataProvider
    arguments:
      - "@dealtmodule.doctrine.dealt.offer.repository"
      - "@dealtmodule.doctrine.dealt.product.repository"
  dealtmodule.admin.form.offer.builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: "prestashop.core.form.builder.form_builder_factory:create"
    arguments:
      - 'DealtModule\Forms\Admin\DealtOfferFormType'
      - "@dealtmodule.admin.form.offer.data.provider"
  dealtmodule.admin.form.offer.data.handler:
    class: 'DealtModule\Forms\Admin\DealtOfferFormDataHandler'
    arguments:
      - "@dealtmodule.doctrine.dealt.offer.repository"
      - "@dealtmodule.doctrine.dealt.product.repository"
  dealtmodule.admin.form.offer.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: "prestashop.core.form.identifiable_object.handler.form_handler_factory:create"
    arguments:
      - "@dealtmodule.admin.form.offer.data.handler"
  ########################################
  ### DEALT OFFER GRID  ##################
  ########################################
  dealtmodule.admin.grid.offer.definition.factory:
    class: 'DealtModule\Core\Grid\Definition\Factory\DealtOfferGridDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
  dealtmodule.admin.grid.offer.query.builder:
    class: 'DealtModule\Core\Grid\Query\DealtOfferQueryBuilder'
    parent: "prestashop.core.grid.abstract_query_builder"
    public: true
  dealtmodule.admin.grid.offer.data.factory:
    class: 'DealtModule\Core\Grid\Data\Factory\DealtOfferGridDataFactory'
    arguments:
      $offerCategoryRepository: "@dealtmodule.doctrine.dealt.offer.category.repository"
      $gridQueryBuilder: "@dealtmodule.admin.grid.offer.query.builder"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $queryParser: "@prestashop.core.grid.query.doctrine_query_parser"
      $gridId: "dealt_offer"
  dealtmodule.admin.grid.offer.factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      $definitionFactory: "@dealtmodule.admin.grid.offer.definition.factory"
      $dataFactory: "@dealtmodule.admin.grid.offer.data.factory"
      $filterFormFactory: "@prestashop.core.grid.filter.form_factory"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
  ########################################
  ### DEALT MISSION GRID  ################
  ########################################
  dealtmodule.admin.grid.mission.definition.factory:
    class: 'DealtModule\Core\Grid\Definition\Factory\DealtMissionGridDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
  dealtmodule.admin.grid.mission.query.builder:
    class: 'DealtModule\Core\Grid\Query\DealtMissionQueryBuilder'
    parent: "prestashop.core.grid.abstract_query_builder"
    public: true
  dealtmodule.admin.grid.mission.data.factory:
    class: 'DealtModule\Core\Grid\Data\Factory\DealtMissionGridDataFactory'
    arguments:
      $offerRepository: "@dealtmodule.doctrine.dealt.offer.repository"
      $missionRepository: "@dealtmodule.doctrine.dealt.mission.repository"
      $gridQueryBuilder: "@dealtmodule.admin.grid.mission.query.builder"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $queryParser: "@prestashop.core.grid.query.doctrine_query_parser"
      $gridId: "dealt_mission"
  dealtmodule.admin.grid.mission.factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      $definitionFactory: "@dealtmodule.admin.grid.mission.definition.factory"
      $dataFactory: "@dealtmodule.admin.grid.mission.data.factory"
      $filterFormFactory: "@prestashop.core.grid.filter.form_factory"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
