services:
  # Dealt Module Installer
  dealtmodule.installer:
    class: DealtModule\Database\DealtInstaller
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"
  ################################
  ### DEALT CONFIGURATION FORM ###
  ################################
  ### DATA PROVIDER ##############
  dealtmodule.admin.form.configuration.provider:
    class: DealtModule\Forms\Admin\DealtConfigurationFormDataProvider
    arguments:
      $configuration: "@prestashop.adapter.legacy.configuration"
  ### FORM HANDLER ###############
  dealtmodule.admin.form.configuration.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $formDataProvider: "@dealtmodule.admin.form.configuration.provider"
      $formTypes:
        configuration: 'DealtModule\Forms\Admin\DealtConfigurationFormType'
      $hookName: "AdminDealtModuleConfiguration"
  ################################
  ### DEALT MISSION GRID  ########
  ################################
  ### GRID DEFINITION FACTORY ####
  dealtmodule.admin.grid.missions.factory:
    class: 'DealtModule\Core\Grid\Definition\Factory\DealtMissionGridDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
    public: true
