services:
  #######################################
  ### DEALT CONFIGURATION FORM ##########
  #######################################
  ### DATA PROVIDER #####################
  dealtmodule.admin.form.configuration.provider:
    class: DealtModule\Forms\Admin\DealtConfigurationFormDataProvider
    arguments:
      $configuration: "@prestashop.adapter.legacy.configuration"
  ### FORM HANDLER ######################
  dealtmodule.admin.form.configuration.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $formDataProvider: "@dealtmodule.admin.form.configuration.provider"
      $formTypes:
        configuration: 'DealtModule\Forms\Admin\DealtConfigurationFormType'
      $hookName: "AdminDealtModuleConfiguration"
  #######################################
  ### DEALT MISSION FORM ################
  #######################################
  ### DATA PROVIDER #####################
  dealtmodule.admin.form.mission.data.provider:
    class: DealtModule\Forms\Admin\DealtMissionFormDataProvider
    arguments:
      - "@dealtmodule.doctrine.dealt.mission.repository"
      - "@dealtmodule.doctrine.dealt.virtual.product.repository"
  ### FORM BUILDER ######################
  dealtmodule.admin.form.mission.builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: "prestashop.core.form.builder.form_builder_factory:create"
    arguments:
      - 'DealtModule\Forms\Admin\DealtMissionFormType'
      - "@dealtmodule.admin.form.mission.data.provider"
  ### FORM DATA HANDLER #################
  dealtmodule.admin.form.mission.data.handler:
    class: 'DealtModule\Forms\Admin\DealtMissionFormDataHandler'
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@dealtmodule.doctrine.dealt.mission.repository"
      - "@dealtmodule.doctrine.dealt.virtual.product.repository"
  ### FORM HANDLER ######################
  dealtmodule.admin.form.mission.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: "prestashop.core.form.identifiable_object.handler.form_handler_factory:create"
    arguments:
      - "@dealtmodule.admin.form.mission.data.handler"
  ########################################
  ### DEALT MISSION GRID  ################
  ########################################
  ### MISSION GRID DEFINITION FACTORY ####
  dealtmodule.admin.grid.missions.definition.factory:
    class: 'DealtModule\Core\Grid\Definition\Factory\DealtMissionGridDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
  ### MISSION GRID QUERY BUILDER #########
  dealtmodule.admin.grid.missions.query.builder:
    class: 'DealtModule\Core\Grid\Query\DealtMissionQueryBuilder'
    parent: "prestashop.core.grid.abstract_query_builder"
    public: true
  ### MISSION GRID DATA FACTORY ##########
  dealtmodule.admin.grid.missions.data.factory:
    class: 'DealtModule\Core\Grid\Data\Factory\DealtMissionGridDataFactory'
    arguments:
      $gridQueryBuilder: "@dealtmodule.admin.grid.missions.query.builder"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
      $queryParser: "@prestashop.core.grid.query.doctrine_query_parser"
      $gridId: "dealt_missions"
  ### MISSION GRID FACTORY ################
  dealtmodule.admin.grid.missions.factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      $definitionFactory: "@dealtmodule.admin.grid.missions.definition.factory"
      $dataFactory: "@dealtmodule.admin.grid.missions.data.factory"
      $filterFormFactory: "@prestashop.core.grid.filter.form_factory"
      $hookDispatcher: "@prestashop.core.hook.dispatcher"
